# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa # optional
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          # config: ${{ secrets.CONFIG }} # ssh_config; optional

      # $GITHUB_REF is available by default. See https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Push to remote repo
        env:
          GIT_REMOTE: ${{ secrets.GIT_REMOTE }}
        run: |
          echo GIT_REMOTE: $GIT_REMOTE
          echo GITHUB_REF: $GITHUB_REF
          echo BRANCH: ${{ steps.extract_branch.outputs.branch }}
          git remote add destination $GIT_REMOTE
          echo git remote -v

# git push ${{ steps.extract_branch.outputs.branch }} $GIT_REMOTE
# Runs a set of commands using the runners shell
# - name: Run a multi-line script
#   env:
#     SSH_KEY: ${{ secrets.SSH_KEY }}
#   run: |
#     echo sshkey: $SSH_KEY
#     echo GITHUB_WORKFLOW: $GITHUB_WORKFLOW
