name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  push_to_remote:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Make sure the @v0.4.1 matches the current version of the
      # action
      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      # $GITHUB_REF is available by default. See https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Push to remote repo
        env:
          GIT_REMOTE_ADDRESS: ${{ secrets.GIT_REMOTE }}
          GIT_REMOTE_NAME: "destination"
        run: |
          yak yak yak yak
          echo GIT_REMOTE_ADDRESS: $GIT_REMOTE_ADDRESS
          echo GIT_REMOTE_NAME: $GIT_REMOTE_NAME
          echo GITHUB_REF: $GITHUB_REF
          echo BRANCH: ${{ steps.extract_branch.outputs.branch }}
          git fetch origin $BRANCH --unshallow
          git remote add $GIT_REMOTE_NAME $GIT_REMOTE_ADDRESS
          git push $GIT_REMOTE_NAME ${{ steps.extract_branch.outputs.branch }}

      - name: Notify Slack on Failure
        if: ${{ failure() }}
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: github-actions-test
